# Generated by Django 5.0.4 on 2026-02-26 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=5)),
                ("decimal_places", models.PositiveSmallIntegerField(default=2)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "currencies",
                "db_table": "currencies",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("iso_code", models.CharField(max_length=2, unique=True)),
                ("iso_code_3", models.CharField(blank=True, max_length=3, unique=True)),
                ("phone_prefix", models.CharField(blank=True, max_length=6)),
                ("default_timezone", models.CharField(default="UTC", max_length=60)),
                ("tax_year_start_month", models.PositiveSmallIntegerField(default=1)),
                ("tax_year_start_day", models.PositiveSmallIntegerField(default=1)),
                ("date_format", models.CharField(default="DD/MM/YYYY", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("flag_emoji", models.CharField(blank=True, max_length=4)),
                (
                    "default_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_for_countries",
                        to="geography.currency",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "countries",
                "db_table": "countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=6, max_digits=18)),
                ("effective_date", models.DateField()),
                (
                    "base_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_rates_base",
                        to="geography.currency",
                    ),
                ),
                (
                    "target_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_rates_target",
                        to="geography.currency",
                    ),
                ),
            ],
            options={
                "db_table": "exchange_rates",
                "ordering": ["-effective_date"],
                "unique_together": {
                    ("base_currency", "target_currency", "effective_date")
                },
            },
        ),
    ]
