# Generated by Django 5.0.4 on 2026-02-26 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "companies",
            "0002_remove_company_district_remove_company_rssb_number_and_more",
        ),
        ("employees", "0002_remove_employee_rssb_number_and_more"),
        ("geography", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "gross_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "deduction_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "employer_contribution_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "net_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="companies.company",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_runs",
                        to="geography.currency",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_payrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_runs",
                "ordering": ["-period_start"],
                "unique_together": {("company", "period_start", "period_end")},
            },
        ),
        migrations.CreateModel(
            name="PayrollLineItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gross_salary", models.DecimalField(decimal_places=2, max_digits=14)),
                ("employee_deductions", models.JSONField(default=dict)),
                ("employer_contributions", models.JSONField(default=dict)),
                (
                    "total_employee_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_employer_contributions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("net_salary", models.DecimalField(decimal_places=2, max_digits=14)),
                ("is_payslip_generated", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_items",
                        to="employees.employee",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="payroll.payrollrun",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_line_items",
                "unique_together": {("payroll_run", "employee")},
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="payslips/%Y/%m/"
                    ),
                ),
                ("is_ready", models.BooleanField(default=False)),
                ("sent_to_employee", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "line_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslip",
                        to="payroll.payrolllineitem",
                    ),
                ),
            ],
            options={
                "db_table": "payslips",
            },
        ),
        migrations.CreateModel(
            name="TaxRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("income_tax", "Income Tax"),
                            ("social_security", "Social Security"),
                            ("pension", "Pension"),
                            ("health_insurance", "Health Insurance"),
                            ("payroll_levy", "Payroll Levy"),
                            ("other", "Other Deduction"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "calc_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Flat Percentage"),
                            ("bracket", "Progressive Brackets"),
                            ("fixed", "Fixed Amount"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict,
                        help_text="Calculation config: rate/brackets/amount + employer split",
                    ),
                ),
                ("applies_to_employee", models.BooleanField(default=True)),
                ("applies_to_employer", models.BooleanField(default=False)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_rules",
                        to="geography.country",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_tax_rules",
                "ordering": ["country", "rule_type", "name"],
            },
        ),
    ]
