# Generated by Django 5.0.4 on 2026-03-20 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_company_industry_company_fiscal_year_start"),
        ("custom_forms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formsubmission",
            options={"ordering": ["-submitted_at"]},
        ),
        migrations.AlterModelOptions(
            name="formtemplate",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="formfield",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="formtemplate",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="formtemplate",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
