# Generated by Django 5.0.4 on 2026-02-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="rssb_number",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="tin_number",
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_branch_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="employee",
            name="nationality",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="social_insurance_number",
            field=models.CharField(
                blank=True,
                help_text="National pension / social security number",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="tax_identifier",
            field=models.CharField(
                blank=True,
                help_text="Employee tax identification number",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Salary currency (defaults to company currency)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="geography.currency",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="national_id",
            field=models.CharField(
                blank=True, help_text="National ID / passport number", max_length=50
            ),
        ),
    ]
