# Generated by Django 5.2.11 on 2026-02-25 19:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('company_type', models.CharField(choices=[('sme', 'Small & Medium Enterprise'), ('ngo', 'NGO'), ('accounting', 'Accounting Firm'), ('hr_consultancy', 'HR Consultancy'), ('other', 'Other')], default='sme', max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('tin_number', models.CharField(blank=True, help_text='RRA Tax Identification Number', max_length=50)),
                ('rssb_number', models.CharField(blank=True, help_text='RSSB employer number', max_length=50)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(default='Rwanda', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('primary_color', models.CharField(default='#1a56db', max_length=7)),
                ('subscription_plan', models.CharField(choices=[('free', 'Free (up to 10 employees)'), ('starter', 'Starter (up to 50)'), ('professional', 'Professional (up to 200)'), ('enterprise', 'Enterprise (unlimited)')], default='free', max_length=20)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
    ]
