# Generated by Django 5.0.4 on 2026-02-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="district",
        ),
        migrations.RemoveField(
            model_name="company",
            name="rssb_number",
        ),
        migrations.RemoveField(
            model_name="company",
            name="tin_number",
        ),
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Operating currency (defaults to country default if blank)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to="geography.currency",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="company",
            name="social_security_identifier",
            field=models.CharField(
                blank=True,
                help_text="Employer registration number for your national social security authority",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="state_province",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="tax_identifier",
            field=models.CharField(
                blank=True,
                help_text="Tax Identification Number (TIN/EIN/UTR) issued by your national tax authority",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="timezone",
            field=models.CharField(
                blank=True,
                help_text="IANA timezone (e.g. America/New_York). Defaults to country timezone.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("sme", "Small & Medium Enterprise"),
                    ("ngo", "NGO / Non-Profit"),
                    ("accounting", "Accounting Firm"),
                    ("hr_consultancy", "HR Consultancy"),
                    ("healthcare", "Healthcare"),
                    ("construction", "Construction"),
                    ("technology", "Technology"),
                    ("manufacturing", "Manufacturing"),
                    ("other", "Other"),
                ],
                default="sme",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to="geography.country",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="registration_number",
            field=models.CharField(
                blank=True,
                help_text="Company/business registration number issued by your national registry",
                max_length=50,
            ),
        ),
    ]
