# Generated by Django 5.2.11 on 2026-02-25 19:59

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('employment_contract', 'Employment Contract'), ('contract_amendment', 'Contract Amendment'), ('nda', 'Non-Disclosure Agreement'), ('rra_filing', 'RRA Tax Filing'), ('rssb_declaration', 'RSSB Declaration'), ('paye_return', 'PAYE Return'), ('vat_return', 'VAT Return'), ('payslip', 'Payslip'), ('warning_letter', 'Warning Letter'), ('leave_form', 'Leave Form'), ('termination_letter', 'Termination Letter'), ('business_registration', 'Business Registration'), ('tax_clearance', 'Tax Clearance Certificate'), ('audit_report', 'Audit Report'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 of encrypted file', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('active', 'Active'), ('expired', 'Expired'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('extracted_text', models.TextField(blank=True)),
                ('ocr_processed', models.BooleanField(default=False)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='employees.employee')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'document_type'], name='documents_company_654c10_idx'), models.Index(fields=['company', 'status'], name='documents_company_1c619b_idx'), models.Index(fields=['expiry_date'], name='documents_expiry__8f271f_idx'), models.Index(fields=['employee', 'document_type'], name='documents_employe_fcf392_idx')],
            },
        ),
    ]
