# Generated by Django 5.0.4 on 2026-02-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("employment_contract", "Employment Contract"),
                    ("contract_amendment", "Contract Amendment"),
                    ("nda", "Non-Disclosure Agreement"),
                    ("tax_filing", "Tax Filing"),
                    ("social_security_declaration", "Social Security Declaration"),
                    ("payroll_tax_return", "Payroll Tax Return"),
                    ("vat_return", "VAT / Sales Tax Return"),
                    ("tax_clearance", "Tax Clearance Certificate"),
                    ("payslip", "Payslip"),
                    ("warning_letter", "Warning Letter"),
                    ("leave_form", "Leave Form"),
                    ("termination_letter", "Termination Letter"),
                    ("business_registration", "Business Registration"),
                    ("operating_license", "Operating License"),
                    ("audit_report", "Audit Report"),
                    ("financial_statement", "Financial Statement"),
                    ("insurance_certificate", "Insurance Certificate"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
