# Generated by Django 5.2.11 on 2026-02-25 19:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('audit_readiness', 'Audit Readiness Report'), ('employee_summary', 'Employee Summary'), ('compliance_status', 'Compliance Status'), ('payroll_summary', 'Payroll Summary'), ('document_inventory', 'Document Inventory'), ('rra_filing', 'RRA Filing Summary'), ('rssb_filing', 'RSSB Filing Summary')], max_length=30)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('parameters', models.JSONField(default=dict)),
                ('is_ready', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
