# Generated by Django 5.0.4 on 2026-02-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("audit_readiness", "Audit Readiness Report"),
                    ("employee_summary", "Employee Summary"),
                    ("compliance_status", "Compliance Status"),
                    ("payroll_summary", "Payroll Summary"),
                    ("payroll_run_detail", "Payroll Run Detail"),
                    ("document_inventory", "Document Inventory"),
                    ("tax_filing_summary", "Tax Filing Summary"),
                    ("social_security_summary", "Social Security Summary"),
                    ("financial_summary", "Financial Summary"),
                ],
                max_length=30,
            ),
        ),
    ]
