# Generated by Django 5.0.4 on 2026-03-20 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_company_industry_company_fiscal_year_start"),
        ("signatures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signaturerequest",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="companies.company",
            ),
        ),
    ]
