# Generated by Django 5.2.11 on 2026-02-25 19:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('authority', models.CharField(blank=True, help_text='e.g. RRA, RSSB, RDB', max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'compliance categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('frequency', models.CharField(choices=[('one_time', 'One-Time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('as_needed', 'As Needed')], max_length=20)),
                ('deadline_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of month deadline (e.g. 15 for 15th)', null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('document_types_required', models.JSONField(default=list, help_text='List of document type codes needed')),
                ('penalty_description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='compliance.compliancecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('overdue', 'Overdue'), ('pending', 'Pending'), ('exempt', 'Exempt'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evidence_documents', models.ManyToManyField(blank=True, to='documents.document')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.compliancerequirement')),
            ],
            options={
                'db_table': 'compliance_records',
                'ordering': ['due_date'],
                'unique_together': {('company', 'requirement', 'period_start')},
            },
        ),
    ]
