# Generated by Django 5.0.4 on 2026-02-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancerecord",
            name="risk_score",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="0-100 risk score; higher = more risk"
            ),
        ),
        migrations.AddField(
            model_name="compliancerequirement",
            name="industry_applicability",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Empty = all industries; otherwise list of industry codes",
            ),
        ),
        migrations.AlterField(
            model_name="compliancecategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="compliancerequirement",
            name="deadline_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Day of month deadline (e.g. 15 = 15th of each period)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="compliancerequirement",
            name="document_types_required",
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name="Authority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "short_name",
                    models.CharField(
                        blank=True, help_text="e.g. IRS, HMRC, KRA", max_length=20
                    ),
                ),
                (
                    "authority_type",
                    models.CharField(
                        choices=[
                            ("tax", "Tax Authority"),
                            ("social_security", "Social Security"),
                            ("labor", "Labour / Employment"),
                            ("corporate", "Corporate / Business Registry"),
                            ("environmental", "Environmental"),
                            ("financial", "Financial Regulator"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("api_available", models.BooleanField(default=False)),
                ("api_config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for platform-wide / universal authorities",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorities",
                        to="geography.country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "authorities",
                "db_table": "compliance_authorities",
                "ordering": ["country__name", "name"],
                "unique_together": {("country", "short_name")},
            },
        ),
        migrations.AlterField(
            model_name="compliancecategory",
            name="authority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="compliance.authority",
            ),
        ),
    ]
